name: Auto Comment Reply

on:
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
      
jobs:
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --save axios
      - name: Cache
        uses: actions/cache@v3      
        with:
          key: node_modules
          path: node_modules        
      - name: Comment Issue
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });            
            const fs = require('fs');
            const axios = require('axios');            
            const prompt = {
              "prompt": fs.readFileSync('./README.md').toString() + "\n\nAnswer the following question from the text above.\n\nQ: " + context.payload.comment.body + "\nA:",
              "temperature": 0.7,
              "top_p": 1,
              "frequency_penalty": 0,
              "presence_penalty": 0,
              "max_tokens": 256,
              "stop": [
                "\n"
              ]
            }
            const res = await axios.post('https://alexvieiopenai.openai.azure.com/openai/deployments/model1/completions?api-version=2022-12-01', JSON.stringify(prompt), {
              headers: {
                'Content-Type': 'application/json',
                'api-key': '${{ secrets.OPENAI_API_KEY }}'
              }
            })
              .catch(err => {
                console.log('Error: ', err.message);
              });
              
            console.log('Response: ', res);
            github.issues.createComment({
              issue_number: context.issue.number,
              owner,
              repo,
              body: res.data.choices[0].text,
            });
